[package]
name = "tts-server"
version = "0.1.0"
authors = ["litcc"]
edition = "2021"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#messagebus = "0.9.10"
#vertx-rust = "0.3.0"
crossbeam-channel = "0.5.2" # 队列库
num_cpus = "1.13.1" # 获取cpu信息
fancy-regex = "0.7.1" # 正则库
log = "0.4.14" # 日志库
log4rs = "1.0.0" # 日志扩展库
env_logger="0.9.0" # 日志扩展库
uuid = { version = "0.8.2", features = ["v4"] } # uuid库
rand = "0.8.4" # 随机数库
futures-util = "0.3.19" # 异步工具库
once_cell = "1.9.0"
bytes = "1.1.0"
serde = "1.0.133"
actix-web = "3"
anyhow = "1.0"
rustls = { version = "0.20.2", default-features = false }
tokio-rustls = "0.23.2"
rustls-native-certs = "0.6.1"
#tungstenite = {version = "^0.15.0", features = ["__rustls-tls"]}
tokio-tungstenite = {version = "0.16.1", features = ["__rustls-tls"]}
#tokio-tungstenite = "0.16.0"
tokio = { version = "1.15.0", features = ["full"] } # 协程库
#[dependencies.vertx-rust]
#git = 'https://github.com/kathog/vertx-rust.git'
#rev = '80d67580e7081129fcc39325d6d9de37eb053a06'
#version = '0.2.2'


[dev-dependencies]



