[package]
name = "tts-server"
version = "0.1.1"
authors = ["litcc"]
edition = "2021"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }  # 命令行解析库
num_cpus = "1.13.1"  # 获取cpu信息
itertools = "0.10.3"  # 迭代器工具库
fancy-regex = "0.7.1"  # 正则库
log = "0.4.14"  # 日志库
log4rs = "1.0.0"  # 日志扩展库
env_logger = "0.9.0"  # 日志扩展库
num = "0.4.0"  #计算库
uuid = { version = "0.8.2", features = ["v4"] }  # uuid库
urlencoding = "2.1.0"  # url编码解析库
rand = "0.8.4"  # 随机数库
futures-util = "0.3.19"  # 异步工具库
reqwest = { version = "0.11.9", features = ["json", "rustls-tls-native-roots"] }  # http 请求库
once_cell = "1.9.0"
bytes = "1.1.0"
serde = "1.0.136"
serde_json = "1.0.78"
#json = "0.12.4"
bincode = "1.3.3"
actix-web = "3.3.3"
actix-rt = "2.6.0"
#anyhow = "1.0"
rustls = { version = "0.20.2", default-features = false }
tokio-rustls = "0.23.2"
rustls-native-certs = "0.6.1"
#tungstenite = {version = "^0.15.0", features = ["__rustls-tls"]}
tokio-tungstenite = { version = "0.16.1", features = ["__rustls-tls"] }
#tokio-tungstenite = "0.16.0"
tokio = { version = "1.16.1", features = ["full"] } # 协程库
event_bus = { git = "https://github.com/litcc/event_bus.git" }
local_ipaddress = "0.1.3"  # 获取本地ip


[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'